### ISSUE TITLE
torch>=2.4 dependency in dev means no support for Intel Macs

### ISSUE THREAD

**Issue by ajkessel** [idiap/coqui-ai-TTS#112]
### Describe the bug

torch stopped building for Intel Macs after 2.2.2. coqui-tts main branch still installs because it only requires torch>=2.1, but on dev you are requiring torch>=2.4, and thus it cannot be installed even on a relatively recent Mac (e.g. iMac (Retina 5K, 27-inch, 2020)). Do you need the >=2.4 requirement or could it be loosened?

### To Reproduce

Attempt to install from dev

### Environment

```shell
{
    "CUDA": {
        "GPU": [],
        "available": false,
        "version": null
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.2.2",
        "TTS": "0.24.2",
        "numpy": "1.26.4"
    },
    "System": {
        "OS": "Darwin",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "i386",
        "python": "3.11.10",
        "version": "Darwin Kernel Version 24.0.0: Tue Sep 24 23:36:30 PDT 2024; root:xnu-11215.1.12~1/RELEASE_X86_64"
    }
}
```

**Comment by eginhard** [comment]
Yeah, I agree it's not ideal. I've started adding some conditional handling for the code that needed this in https://github.com/idiap/coqui-ai-Trainer/pull/11, after which I can do the same in this repo and go back down to 2.1

**Comment by eginhard** [comment]
The minimum Pytorch version is now back to 2.1 (2.3 if using Python 3.12).
