### ISSUE TITLE
[Bug] Mix language inference text

### ISSUE THREAD

**Issue by cod3r0k** [idiap/coqui-ai-TTS#115]
### Describe the bug

What should we do for text that contains multiple languages? Since inference sends everything to eSpeak with a fixed language setting, eSpeak does not handle it well!

### To Reproduce

Since inference sends everything to eSpeak with a fixed language setting, eSpeak does not handle it well!

### Expected behavior

well phonemizer working

### Environment

```shell
What should we do for text that contains multiple languages? Since inference sends everything to eSpeak with a fixed language setting, eSpeak does not handle it well!
```

**Comment by eginhard** [comment]
Yes, there is currently no way to do this directly in Coqui. But you can do mixed-language TTS with Vits/YourTTS models if you add some custom code (including calling Espeak separately per language if you don't use grapheme-based models), see #104 for details.

Integrating this would first need SSML support (see previous discussions in https://github.com/coqui-ai/TTS/issues/752), which is very complex, so closing as not planned for now, but I'm open to contributions regarding SSML.

**Comment by cod3r0k** [comment]
Hi, I check espeak with Persian (fa) language. I found that it handle English also. Isnt it enough? @eginhard

**Comment by cod3r0k** [comment]
For the first run, yes Just Persian and English. 
maybe Arabic in the next version.
in the last one, Germany (it is different from all of them)

But step by step. for the first step (Persian and English), do you have any concern?
