### ISSUE TITLE
Unclear error message with multi-channel audio

### ISSUE THREAD

**Issue by madey83** [idiap/coqui-ai-TTS#153]
### Describe the bug

(TTS-Training) PS D:\TTS-Training\Vits-PL-Model-training> python train_vits_win_Thorsten-Voice.py
 > Training Environment:
 | > Backend: Torch
 | > Mixed precision: False
 | > Precision: float32
 | > Current device: 0
 | > Num. of GPUs: 1
 | > Num. of CPUs: 12
 | > Num. of Torch Threads: 6
 | > Torch seed: 54321
 | > Torch CUDNN: True
 | > Torch CUDNN deterministic: False
 | > Torch CUDNN benchmark: False
 | > Torch TF32 MatMul: False
 > Start Tensorboard: tensorboard --logdir=D:\TTS-Training\Vits-PL-Model-training\Output\Vits-TTS-PL-November-12-2024_12+11PM-0000000

 > Model has 83059180 parameters

 > EPOCH: 0/1000
 --> D:\TTS-Training\Vits-PL-Model-training\Output\Vits-TTS-PL-November-12-2024_12+11PM-0000000

 > TRAINING (2024-11-12 12:11:32)
D:\TTS-Training\TTS-Training\coqui-ai-TTS\TTS\tts\models\vits.py:1280: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=False):  # use float32 for the criterion
D:\TTS-Training\TTS-Training\coqui-ai-TTS\TTS\tts\models\vits.py:1291: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=False):
D:\TTS-Training\TTS-Training\coqui-ai-TTS\TTS\tts\models\vits.py:1318: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=False):  # use float32 for the criterion

   --> TIME: 2024-11-12 12:12:02 -- STEP: 0/759 -- GLOBAL_STEP: 0
     | > loss_disc: 5.956424236297607  (5.956424236297607)
     | > loss_disc_real_0: 0.983599841594696  (0.983599841594696)
     | > loss_disc_real_1: 0.9864199161529541  (0.9864199161529541)
     | > loss_disc_real_2: 1.0203317403793335  (1.0203317403793335)
     | > loss_disc_real_3: 0.9715399742126465  (0.9715399742126465)
     | > loss_disc_real_4: 1.0096056461334229  (1.0096056461334229)
     | > loss_disc_real_5: 0.9844017028808594  (0.9844017028808594)
     | > loss_0: 5.956424236297607  (5.956424236297607)
     | > grad_norm_0: tensor(6.5297, device='cuda:0')  (tensor(6.5297, device='cuda:0'))
     | > loss_gen: 4.573174476623535  (4.573174476623535)
     | > loss_kl: 175.9973907470703  (175.9973907470703)
     | > loss_feat: 0.36679768562316895  (0.36679768562316895)
     | > loss_mel: 118.89251708984375  (118.89251708984375)
     | > loss_duration: 1.9684126377105713  (1.9684126377105713)
     | > loss_1: 301.7983093261719  (301.7983093261719)
     | > grad_norm_1: tensor(1292.4227, device='cuda:0')  (tensor(1292.4227, device='cuda:0'))
     | > current_lr_0: 0.0002
     | > current_lr_1: 0.0002
     | > step_time: 3.4077  (3.407663583755493)
     | > loader_time: 26.5631  (26.56307864189148)

Traceback (most recent call last):
  File "D:\TTS-Training\TTS-Training\lib\site-packages\trainer\trainer.py", line 1605, in fit
    self._fit()
  File "D:\TTS-Training\TTS-Training\lib\site-packages\trainer\trainer.py", line 1557, in _fit
    self.train_epoch()
  File "D:\TTS-Training\TTS-Training\lib\site-packages\trainer\trainer.py", line 1272, in train_epoch
    for cur_step, batch in enumerate(self.train_loader):
  File "D:\TTS-Training\TTS-Training\lib\site-packages\torch\utils\data\dataloader.py", line 701, in __next__
    data = self._next_data()
  File "D:\TTS-Training\TTS-Training\lib\site-packages\torch\utils\data\dataloader.py", line 1465, in _next_data
    return self._process_data(data)
  File "D:\TTS-Training\TTS-Training\lib\site-packages\torch\utils\data\dataloader.py", line 1491, in _process_data
    data.reraise()
  File "D:\TTS-Training\TTS-Training\lib\site-packages\torch\_utils.py", line 715, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "D:\TTS-Training\TTS-Training\lib\site-packages\torch\utils\data\_utils\worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "D:\TTS-Training\TTS-Training\lib\site-packages\torch\utils\data\_utils\fetch.py", line 55, in fetch
    return self.collate_fn(data)
  File "D:\TTS-Training\TTS-Training\coqui-ai-TTS\TTS\tts\models\vits.py", line 350, in collate_fn
    wav_padded[i, :, : wav.size(1)] = torch.FloatTensor(wav)
RuntimeError: The expanded size of the tensor (1) must match the existing size (2) at non-singleton dimension 0.  Target sizes: [1, 16978].  Tensor sizes: [2, 16978]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\TTS-Training\Vits-PL-Model-training\train_vits_win_Thorsten-Voice.py", line 101, in <module>
    main()
  File "D:\TTS-Training\Vits-PL-Model-training\train_vits_win_Thorsten-Voice.py", line 95, in main
    trainer.fit()
  File "D:\TTS-Training\TTS-Training\lib\site-packages\trainer\trainer.py", line 1632, in fit
    remove_experiment_folder(self.output_path)
  File "D:\TTS-Training\TTS-Training\lib\site-packages\trainer\generic_utils.py", line 78, in remove_experiment_folder
    fs.rm(experiment_path, recursive=True)
  File "D:\TTS-Training\TTS-Training\lib\site-packages\fsspec\implementations\local.py", line 172, in rm
    shutil.rmtree(p)
  File "C:\Users\Lucky38\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Lucky38\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 629, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\Lucky38\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 627, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:/TTS-Training/Vits-PL-Model-training/Output/Vits-TTS-PL-November-12-2024_12+11PM-0000000\\trainer_0_log.txt'
(TTS-Training) PS D:\TTS-Training\Vits-PL-Model-training>

### To Reproduce

execute py script

### Expected behavior

py recipe:

import os

from trainer import Trainer, TrainerArgs

from TTS.tts.configs.shared_configs import BaseDatasetConfig
from TTS.tts.configs.vits_config import VitsConfig
from TTS.tts.datasets import load_tts_samples
from TTS.tts.models.vits import Vits, VitsAudioConfig
from TTS.tts.utils.text.tokenizer import TTSTokenizer
from TTS.utils.audio import AudioProcessor

def main():

	#output_path = os.path.dirname(os.path.abspath(__file__))
	output_path = "D:\\TTS-Training\\Vits-PL-Model-training\\Output"
	dataset_config = BaseDatasetConfig(
		formatter="ljspeech", meta_file_train="metadata.csv", path="D:\\TTS-Training\\Vits-PL-Model-training\\dataLJSpeech_final"
	)
	audio_config = VitsAudioConfig(
		sample_rate=22050, win_length=1024, hop_length=256, num_mels=80, mel_fmin=0, mel_fmax=None
	)
        
	config = VitsConfig(
		audio=audio_config,
		run_name="Vits-TTS-PL",
        #batch_size=24,
        #eval_batch_size=12,
        #batch_group_size=5,
        #num_loader_workers=4,
        #num_eval_loader_workers=4,
		batch_size=24,
		eval_batch_size=12,
		batch_group_size=5,
		num_loader_workers=2,
		num_eval_loader_workers=2,
		run_eval=True,
		test_delay_epochs=-1,
		epochs=1000,
        save_step=1000,
        save_checkpoints=True,
        save_n_checkpoints=2,
        save_best_after=1000,
        add_blank=True,                      
		text_cleaner="multilingual_cleaners",
		use_phonemes=True,
		phoneme_language="pl",
		phoneme_cache_path=os.path.join(output_path, "phoneme_cache"),
		compute_input_seq_cache=True,
		print_step=25,
		print_eval=True,
		mixed_precision=False,
		output_path=output_path,
		datasets=[dataset_config],
		cudnn_benchmark=False,
		test_sentences=[
            "Nazywam się Rusty Sabich i jestem prokuratorem w tym procesie.",
            "Jeśli uznacie to za bardzo prawdopodobne, musicie wypuścić LEDU 20 października 1963 roku.",
		],
	)

	# INITIALIZE THE AUDIO PROCESSOR
	# Audio processor is used for feature extraction and audio I/O.
	# It mainly serves to the dataloader and the training loggers.
	ap = AudioProcessor.init_from_config(config)

	# INITIALIZE THE TOKENIZER
	# Tokenizer is used to convert text to sequences of token IDs.
	# config is updated with the default characters if not defined in the config.
	tokenizer, config = TTSTokenizer.init_from_config(config)

	# LOAD DATA SAMPLES
	# Each sample is a list of ```[text, audio_file_path, speaker_name]```
	# You can define your custom sample loader returning the list of samples.
	# Or define your custom formatter and pass it to the `load_tts_samples`.
	# Check `TTS.tts.datasets.load_tts_samples` for more details.
	train_samples, eval_samples = load_tts_samples(
		dataset_config,
		eval_split=True,
		eval_split_max_size=config.eval_split_max_size,
		eval_split_size=config.eval_split_size,
	)

	# init model
	model = Vits(config, ap, tokenizer, speaker_manager=None)

	# init the trainer and 🚀
	trainer = Trainer(
		TrainerArgs(),
		config,
		output_path,
		model=model,
		train_samples=train_samples,
		eval_samples=eval_samples,
	)
	trainer.fit()
	print("Complete!")

from multiprocessing import Process, freeze_support
if __name__ == '__main__':
    freeze_support()  # needed for Windows
    main()

RTX 2060

### Logs

```shell
Package                 Version      Editable project location
----------------------- ------------ -----------------------------------------
absl-py                 2.1.0
aiohappyeyeballs        2.4.3
aiohttp                 3.10.10
aiosignal               1.3.1
annotated-types         0.7.0
anyascii                0.3.2
async-timeout           4.0.3
attrs                   24.2.0
audioread               3.0.1
babel                   2.16.0
blis                    0.7.11
catalogue               2.0.10
certifi                 2024.8.30
cffi                    1.17.1
charset-normalizer      3.4.0
cleantext               1.1.4
click                   8.1.7
cloudpathlib            0.20.0
cmudict                 1.0.31
colorama                0.4.6
confection              0.1.5
contourpy               1.3.0
coqpit                  0.0.17
coqui-tts               0.24.2       D:\TTS-Training\TTS-Training\coqui-ai-TTS
coqui-tts-trainer       0.1.5
cycler                  0.12.1
cymem                   2.0.8
Cython                  3.0.11
dateparser              1.1.8
decorator               5.1.1
docopt                  0.6.2
einops                  0.8.0
encodec                 0.1.1
ffmpeg                  1.4
ffmpeg-python           0.2.0
filelock                3.13.1
fonttools               4.54.1
frozenlist              1.5.0
fsspec                  2024.2.0
future                  1.0.0
grpcio                  1.67.0
gruut                   2.4.0
gruut-ipa               0.13.0
gruut_lang_de           2.0.1
gruut_lang_en           2.0.1
gruut_lang_es           2.0.1
gruut_lang_fr           2.0.2
huggingface-hub         0.26.1
idna                    3.10
importlib_metadata      8.5.0
importlib_resources     6.4.5
inflect                 7.4.0
Jinja2                  3.1.3
joblib                  1.4.2
jsonlines               1.2.0
kiwisolver              1.4.7
langcodes               3.4.1
language_data           1.2.0
lazy_loader             0.4
librosa                 0.10.2.post1
llvmlite                0.43.0
marisa-trie             1.2.1
Markdown                3.7
markdown-it-py          3.0.0
MarkupSafe              2.1.5
matplotlib              3.9.2
mdurl                   0.1.2
more-itertools          10.5.0
mpmath                  1.3.0
msgpack                 1.1.0
multidict               6.1.0
murmurhash              1.0.10
networkx                3.2.1
nltk                    3.9.1
num2words               0.5.13
numba                   0.60.0
numpy                   1.26.3
openai-whisper          20240930
packaging               24.1
pandas                  2.2.3
pillow                  10.2.0
pip                     24.3.1
platformdirs            4.3.6
pooch                   1.8.2
preshed                 3.0.9
propcache               0.2.0
protobuf                5.28.3
psutil                  6.1.0
pycparser               2.22
pydantic                2.9.2
pydantic_core           2.23.4
pydub                   0.25.1
Pygments                2.18.0
pyparsing               3.2.0
pysbd                   0.3.4
python-crfsuite         0.9.11
python-dateutil         2.9.0.post0
pytz                    2024.2
PyYAML                  6.0.2
regex                   2024.9.11
requests                2.32.3
rich                    13.9.3
safetensors             0.4.5
scikit-learn            1.5.2
scipy                   1.13.1
seaborn                 0.13.2
setuptools              75.3.0
shellingham             1.5.4
six                     1.16.0
smart-open              7.0.5
soundfile               0.12.1
soxr                    0.5.0.post1
spacy                   3.7.5
spacy-legacy            3.0.12
spacy-loggers           1.0.5
srsly                   2.4.8
SudachiDict-core        20241021
SudachiPy               0.6.8
sympy                   1.13.1
tensorboard             2.18.0
tensorboard-data-server 0.7.2
thinc                   8.2.5
threadpoolctl           3.5.0
tiktoken                0.8.0
tokenizers              0.20.1
torch                   2.5.0+cu124
torchaudio              2.5.0+cu124
torchvision             0.20.0+cu124
tqdm                    4.66.5
transformers            4.46.0
typeguard               4.4.0
typer                   0.12.5
typing_extensions       4.12.2
tzdata                  2024.2
tzlocal                 5.2
urllib3                 2.2.3
wasabi                  1.1.3
weasel                  0.4.1
Werkzeug                3.0.6
wheel                   0.45.0
whisper                 1.1.10
wrapt                   1.16.0
yarl                    1.16.0
zipp                    3.20.2
```

### Environment

```shell
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 2060"
        ],
        "available": true,
        "version": "12.4"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.5.0+cu124",
        "TTS": "0.24.2",
        "numpy": "1.26.3"
    },
    "System": {
        "OS": "Windows",
        "architecture": [
            "64bit",
            "WindowsPE"
        ],
        "processor": "Intel64 Family 6 Model 165 Stepping 2, GenuineIntel",
        "python": "3.9.13",
        "version": "10.0.19045"
    }
}
```

### Additional context

![image](https://github.com/user-attachments/assets/2b87cad4-59b8-415c-8779-fa73a6bd472f)

**Comment by ParadoxTR** [comment]
Do you have Stereo voice data or Mono?

**Comment by madey83** [comment]
mono 22050

my dataset looks like:
![image](https://github.com/user-attachments/assets/08ce3daa-57ed-4c36-beec-da3415ce4259)

**Comment by ParadoxTR** [comment]
Okay, then i dont know, but i had same the issue and when i checked twice, i found out my data was stereo.

**Comment by eginhard** [comment]
@madey83 Yes, based on `RuntimeError: The expanded size of the tensor (1) must match the existing size (2) at non-singleton dimension 0. Target sizes: [1, 16978]. Tensor sizes: [2, 16978]` your files likely have 2 channels. If you do "Right click -> Properties" (or whatever it's called) on them it probably shows Stereo...

Perhaps the error message could be improved here.

**Comment by madey83** [comment]
ok. i can check all my wavs, but is there any python script which could validate over 18k wavs files?

**Comment by madey83** [comment]
i have examinated by this scripts my wavs and indead where 2 channels

# Ścieżka do programu ffmpeg (w tym przypadku używamy ffprobe)
$ffprobePath = "D:\Apps\_new\ffmpeg-7.1-full_build\bin\ffprobe.exe"

# Sprawdź, czy ffprobe jest dostępny
if (!(Test-Path $ffprobePath)) {
    Write-Host "FFprobe nie został znaleziony w podanej lokalizacji: $ffprobePath"
    exit
}

# Ścieżka do katalogu z plikami WAV do sprawdzenia
$wavDirectoryPath = "D:\TTS-Training\LJSpeech-1.1\wavs"

# Sprawdź, czy katalog istnieje
if (!(Test-Path $wavDirectoryPath)) {
    Write-Host "Katalog z plikami WAV nie został znaleziony w podanej lokalizacji: $wavDirectoryPath"
    exit
}

# Ścieżka do katalogu, do którego przeniesiemy pliki stereo (2 kanały)
$stereoDirectoryPath = Join-Path $wavDirectoryPath "2channels"

# Utwórz katalog "2channels" jeśli nie istnieje
if (!(Test-Path $stereoDirectoryPath)) {
    New-Item -ItemType Directory -Path $stereoDirectoryPath | Out-Null
}

# Przetwarzanie wszystkich plików WAV w katalogu
Get-ChildItem -Path $wavDirectoryPath -Filter *.wav | ForEach-Object {
    $wavFilePath = $_.FullName
    
    # Uruchomienie ffprobe i pobranie informacji o liczbie kanałów
    $ffprobeOutput = & $ffprobePath -v error -show_entries stream=channels -of default=noprint_wrappers=1:nokey=1 "$wavFilePath" 2>&1
    
    # Analiza wyjścia, aby określić liczbę kanałów
    if ($ffprobeOutput) {
        $channels = [int]$ffprobeOutput.Trim()
        
        # Wyświetlenie informacji o liczbie kanałów i przeniesienie pliku stereo
        if ($channels -eq 1) {
            Write-Host "Plik $wavFilePath jest mono (1 kanał)."
        } elseif ($channels -eq 2) {
            Write-Host "Plik $wavFilePath jest stereo (2 kanały) - przenoszenie do katalogu 2channels."
            
            # Przeniesienie pliku do katalogu 2channels
            $destinationPath = Join-Path $stereoDirectoryPath $_.Name
            Move-Item -Path $wavFilePath -Destination $destinationPath -Force
        } else {
            Write-Host "Plik $wavFilePath ma $channels kanałów."
        }
    } else {
        Write-Host "Nie udało się odczytać liczby kanałów dla pliku $wavFilePath. Upewnij się, że jest to poprawny plik WAV."
    }
}

then i have convert them by this


for /f "tokens=*" %a in ('dir /b *.wav') do ffmpeg -i "%a" -vn -ar 22050 -ac 1 converted_wavs\%~na.wav

so lets check
