### ISSUE TITLE
help

### ISSUE THREAD

**Issue by fontnet1** [idiap/coqui-ai-TTS#225]
Dear friend, I am new to this model and I don't know how to use it. Please introduce me to a video or a roadmap by reading this model and setting it up. How can I use this model and its codes?

Because I want to make a model for Persian.

**Comment by eginhard** [comment]
Please don't create duplicate issues. I already answered in #204

**Comment by fontnet1** [comment]
![Screenshot_۲۰۲۴-۱۲-۱۹-۱۸-۵۵-۵۶-۷۷۷_com.github.android.jpg](https://github.com/user-attachments/assets/e0d92042-dd9d-4527-837f-8f159eb56c53)

Sorry for not answering me

**Comment by eginhard** [comment]
I posted a link to the relevant documentation above the comments in your screenshot. Please don't open further issues here unless you have concrete questions.
