### ISSUE TITLE
Add access to ModelManager and SpeakerManager

### ISSUE THREAD

**Issue by KoljaB** [idiap/coqui-ai-TTS#42]
Hey there,

thanks a lot for maintaining coqui TTS, it's really awesome to have this.

I'm the dev of [RealtimeTTS](https://github.com/KoljaB/RealtimeTTS/) project. In my implementation I'm using these:
```python
from TTS.utils.manage import ModelManager
ModelManager().download_model(model_name)
```
and 

```python
from TTS.utils.generic_utils import get_user_data_dir
from TTS.config import load_config
from TTS.tts.models import setup_model as setup_tts_model
from TTS.tts.layers.xtts.xtts_manager import SpeakerManager
```

I noticed that these are not available any more in the fork. 

Can you please add these back, so we can use ModelManager, SpeakerManager etc directly from the TTS code?

Thanks a lot!

**Comment by eginhard** [comment]
Both code snippets work fine for me with version 0.24.1. Could you share how you installed the package and the full error messages you get?

**Comment by KoljaB** [comment]
Tried to reproduce from scratch (installed with pip), but now I somehow can't recreate. Doesn't happen anymore. Feeling quite dumb now, I'm sorry for your circumstances.

**Comment by eginhard** [comment]
No worries, glad it's working now!
