### ISSUE TITLE
[Bug] Cloning voice add sometimes a noise

### ISSUE THREAD

**Issue by luca2125** [idiap/coqui-ai-TTS#58]
### Describe the bug

The final result of a Italian (but also English) cloning voice add sometimes a annoyed noise.

### To Reproduce

This wetransfer:
https://wetransfer.com/downloads/f8c9dd0ee069e3828d60ad68415a601220240707220325/c77f5f0fbf319e01a8e0e1031c55076b20240707220352/964660 

contain the reference file "mes1603.wav" and the final result "mes1603 (sample result).wav"

the noise is present expecially at 20-24 seconds position.

### Expected behavior

A clone voice without add any noise (the reference file don't contain noise)

### Environment

```shell
TTS Version: xttsv2_2.0.3
PyTorch version: 2.2.1
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro
GCC version: Could not collect

Python version: 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:12:32) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1060 6GB
Nvidia driver version: 537.13
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=1600
DeviceID=CPU0
Family=205
L2CacheSize=11776
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=1600
Name=13th Gen Intel(R) Core(TM) i5-13500T
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] onnxruntime==1.18.1
[pip3] onnxruntime-gpu==1.18.1
[pip3] rotary-embedding-torch==0.6.4
[pip3] torch==2.2.1
[pip3] torch-stoi==0.2.1
[pip3] torchaudio==2.2.1
[pip3] torchcrepe==0.0.23
[pip3] torchvision==0.17.1
[conda] Could not collectpython.exe -m torch.utils.collect_env
```

### Additional context

The TTS version is xttsv2_2.0.3

**Comment by eginhard** [comment]
This is a side effect of how the XTTS model works, not a bug in the code. You could try to synthesise one sentence at a time, but otherwise nothing can be done about this.

**Comment by luca2125** [comment]
Hi Eginhard,

Thank you for your response, only to undestand better:

All models have more or less the some problem ?

Or there is some models where this problem is not preselt ?
