### ISSUE TITLE
[Feature request] installation of package without cuda

### ISSUE THREAD

**Issue by skewty** [idiap/coqui-ai-TTS#80]
**🚀 Feature Description**

Base package installation should not install CUDA (large dependency tree) as some models work fine without it.

**Solution**

Base package doesn't install CUDA and it is installed as an extra.

example: `pip install coqui-tts[cuda]`

**Comment by eginhard** [comment]
I see the point, but I'm not sure if there is a way to do this cleanly? E.g. PyPI only provides the GPU `torch`. In any case, dependencies on CUDA should only be indirectly through Pytorch, so the best workaround is to first manually install the CPU `torch` with the [official instructions](https://pytorch.org/get-started/locally/) to fulfil that dependency and then do `pip install coqui-tts`.

**Comment by eginhard** [comment]
A very late update, but #540 made this possible now. From version 0.27.4, Coqui doesn't install Pytorch by default anymore, making it easier to install the right version for your system yourself. See the updated installation instructions here: https://coqui-tts.readthedocs.io/en/latest/installation.html

There are also new `cpu` and `cuda` extras to install the corresponding Pytorch version, but they only work with [uv](https://docs.astral.sh/uv/) and when installing Coqui from source.
