### ISSUE TITLE
[Feature request] Model quantization

### ISSUE THREAD

**Issue by Xd993571551** [idiap/coqui-ai-TTS#82]
**🚀 Feature Description**

I tried **fine-tuning** a model(**vits**) and found that the resulting model size was too large (800+ MB, model type: vits), but the model downloaded from hugging Face was around 100MB. Is there any difference between them?
So I want to try to reduce the size of the model to reduce the space occupied.
Searching the forums, I found someone else with the same [idea](https://github.com/coqui-ai/TTS/discussions/2991), but it seems that there is no good result.

So will corresponding documents or functions be added later?

**Comment by eginhard** [comment]
No, we don't have any plants to implement quantisation (PRs might be considered though).

You can remove parts of the model that are not needed for inference to reduce the model size, as was done for the public checkpoints: https://github.com/coqui-ai/TTS/discussions/1890
