### ISSUE TITLE
[Feature request] Integrate goruut phonemizer 🚀

### ISSUE THREAD

**Issue by neurlang** [idiap/coqui-ai-TTS#86]
**🚀 Integrate [goruut](https://github.com/neurlang/goruut) phonemizer via the [pygoruut](https://github.com/neurlang/pygoruut) [wrapper](https://pypi.org/project/pygoruut/)** 

I was frustrated when the gruut upstream was not responsive about adding new languages to gruut. So I made something. An IPA phonemizer engine supporting 45 languages and growing. Active upstream. Constantly evolving. An easy to follow guide for a new contributors to add a language. Even word-spaceless languages like Chinese and Japanese are covered, obviously Korean is planned. A builtin support for versioning so that the project can evolve without being burdened by backwards-compatibility forever.

**It would be nice** if the maintainers of coqui upstream could give goruut a chance. I would like to assist with that.

**Comment by neurlang** [comment]
Please see

https://github.com/idiap/coqui-ai-TTS/pull/88

**Comment by neurlang** [comment]
Goruut and Pygoruut 0.1.0 released with support for 64 ISO languages and 5 noniso dialects. Resolve g or ɡ issue (mismatch).

**Comment by eginhard** [comment]
Thank you for the suggestion! This seems to be a very new tool and I wasn't able to find much information about it, e.g. how does it work and what are advantages/disadvantages to Espeak and Gruut? Is it used by any other projects? At this early stage I don't want to take on the maintenance cost of having it integrated in Coqui, but any interested users can refer to the PR #88
