### ISSUE TITLE
[Feature request] FTS (File to speech)

### ISSUE THREAD

**Issue by tigros** [idiap/coqui-ai-TTS#89]
hey,

there outta be a way to convert books to speech with this. say i have a 1 MB text file, typical ebook or w/e, why not make coqui-ai-TTS handle that no problem?

i tried this https://github.com/coqui-ai/TTS/discussions/1101#discussioncomment-9768113 but ends up crashing, "RuntimeError: Calculated padded input size per channel: (4). Kernel size: (5). Kernel size can't be greater than actual input size"

that might be fine for a paragraph, but not whole book.

surely you can tune this to be more solid, handling weird input etc you can get from whole book. i believe it would be very useful for lots of people.

regards

**Comment by eginhard** [comment]
I think the potential use cases for synthesising text from a file are too different that one specific way should be added to Coqui. Writing a wrapper script for your specific application should be straightforward, we do this internally as well.
